### ISSUE TITLE
web.core.external could be extracted to web.[lib|external].botometer

### ISSUE THREAD

**Issue by henriquebastos** [cuducos/bot-followers#6]
The whole external package looks libe a botometer package library that other people could use.

Also I would add the proper import interface via `botometer/__init__.py`.

This would make clear how `core` connects with it.

**Comment by cuducos** [comment]
So true. I was immersed in the code and haven't seen that coming. From my point of view (while coding), `external` made sense because it was a package of wrappers for _external_ APIs (Botometer **and** Tweepy). However, if I got your comment right, Tweepy is merely an implementation detail, right? Good point.

I could rename `external` as `botometer` and offer a wrapper to run Botometer not in a given account (that's what Botometer third-party package does), but in the followers of a given account.

Many thanks for the comment ; )
